//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.12 at 09:06:28 PM EEST 
//


package ua.nure.matchenko.practice7.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Material complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Material">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BladeMaterial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="Handle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;sequence>
 *             &lt;element name="WoodHandle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="WoodType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Material", propOrder = {
    "bladeMaterial",
    "handle",
    "woodHandle",
    "woodType"
})
public class Material {

    @XmlElement(name = "BladeMaterial", required = true)
    protected String bladeMaterial;
    @XmlElement(name = "Handle")
    protected String handle;
    @XmlElement(name = "WoodHandle")
    protected String woodHandle;
    @XmlElement(name = "WoodType")
    protected String woodType;

    /**
     * Gets the value of the bladeMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBladeMaterial() {
        return bladeMaterial;
    }

    /**
     * Sets the value of the bladeMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBladeMaterial(String value) {
        this.bladeMaterial = value;
    }

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandle(String value) {
        this.handle = value;
    }

    /**
     * Gets the value of the woodHandle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoodHandle() {
        return woodHandle;
    }

    /**
     * Sets the value of the woodHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoodHandle(String value) {
        this.woodHandle = value;
    }

    /**
     * Gets the value of the woodType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoodType() {
        return woodType;
    }

    /**
     * Sets the value of the woodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoodType(String value) {
        this.woodType = value;
    }

}
