//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.12 at 09:06:28 PM EEST 
//


package ua.nure.matchenko.practice7.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure.matchenko.practice7 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes
     * for package: ua.nure.matchenko.practice7
     * 
     */
    public ObjectFactory() {
        //constructor
    }

    /**
     * Create an instance of {@link SteelArm }
     * 
     */
    public SteelArm createSteelArm() {
        return new SteelArm();
    }

    /**
     * Create an instance of {@link Knife }
     * 
     */
    public Knife createKnife() {
        return new Knife();
    }

    /**
     * Create an instance of {@link Material }
     * 
     */
    public Material createMaterial() {
        return new Material();
    }

    /**
     * Create an instance of {@link Blade }
     * 
     */
    public Blade createBlade() {
        return new Blade();
    }

    /**
     * Create an instance of {@link Visual }
     * 
     */
    public Visual createVisual() {
        return new Visual();
    }

}
